<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Ghanavats.DotNetAws.Templates</PackageId>
    <PackageVersion>1.1.3</PackageVersion>
    <Title>Ghanavats .NET on AWS Starter Kit</Title>
    <Authors>Saeed Ghanavat</Authors>
    <Description>A configurable .NET solution template for building and deploying serverless APIs on AWS.</Description>
    <PackageTags>Clear Architecture;Vertical Slice;DotNet Template;AWS;CDK;AWS Lambda;DynamoDB</PackageTags>
    <PackageProjectUrl>https://www.nuget.org/packages/Ghanavats.DotNetAws.Templates#readme-body-tab</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ghanavat/dotnet-aws-starter-kit</RepositoryUrl>
    <Copyright>Copyright © 2026 Ghanavats Tech</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    
    <!-- Keep package type as 'Template' to show the package as a template package on nuget.org and make your template available in dotnet new search.-->
    <PackageType>Template</PackageType>
    <TargetFramework>net10.0</TargetFramework>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup>
    <LocalizeTemplates>false</LocalizeTemplates>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TemplateEngine.Tasks" Version="7.0.120" PrivateAssets="all" IsImplicitlyDefined="true" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="content\**\*" Exclude="content\**\bin\**;content\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
